#
# Open-BLDC - Open BrushLess DC Motor Controller
# Copyright (c) 2009-2013 Piotr Esden-Tempski <piotr@esden.net>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. The name of the author may not be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
# OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
# THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

COMMON_OBJECTS = driver/mcu.o driver/led.o

OBJECTS = $(COMMON_OBJECTS)

DEFAULT_TARGET = test_blink

test_blink.OBJECTS = \
	test/blink_main.o

OBJECTS += $(test_blink.OBJECTS)

TARGETS += test_blink

test_sys_tick.OBJECTS = \
	test/sys_tick_main.o \
	driver/sys_tick.o

OBJECTS += $(test_sys_tick.OBJECTS)

TARGETS += test_sys_tick

test_usart.OBJECTS = \
	test/usart_main.o \
	driver/usart.o

OBJECTS += $(test_usart.OBJECTS)

TARGETS += test_usart

test_governor.OBJECTS = \
	test/governor_main.o \
	test/gprot_test_governor.o \
	driver/usart.o

OBJECTS += $(test_governor.OBJECTS)

TARGETS += test_governor

test_semihost.OBJECTS = \
	test/semihost_main.o

test_semihost.SEMIHOSTING = 1

OBJECTS += $(test_semihost.OBJECTS)

TARGETS += test_semihost

test_pwm_comm.OBJECTS = \
	test/pwm_comm_main.o \
	driver/pwm.o

OBJECTS += $(test_pwm_comm.OBJECTS)

TARGETS += test_pwm_comm

test_pwm_duty.OBJECTS = \
	test/pwm_duty_main.o \
	driver/pwm.o

OBJECTS += $(test_pwm_duty.OBJECTS)

TARGETS += test_pwm_duty